#!/usr/bin/env python3
"""Generate pufferroyale/csrc/pr_arena_db.h from data/source/royalesim-arena.json.

The source is RoyaleSim's extraction of the shipped (2018) tilemap: a 36x64 grid of
HALF-tile cells (500 millitiles), bits LANE_LEFT=1, LANE_RIGHT=2, NO_DEPLOY=16,
WATER=32 (SPEC §3). We emit:

  PR_CELL_BITS[64][36]   the raw half-cell bitmask (row = y / 500, col = x / 500)
  PR_TILE_FLAGS[32][18]  per whole tile (engine frame): PR_TF_WATER if any of its 4
                         half-cells is water, PR_TF_NODEPLOY if any has the no-deploy bit
  crown tower centres    derived from the king blocks and bridge centres, checked
                         against SPEC §3

Deterministic, re-runnable: `make gen` twice gives byte-identical output.
Usage: python tools/gen_arena.py [--check]
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "source" / "royalesim-arena.json"
OUT = ROOT / "pufferroyale" / "csrc" / "pr_arena_db.h"

# SPEC §3: princess tower y is a rule, not in the tilemap.
PRINCESS_Y_TOP = 6500
PRINCESS_Y_BOTTOM = 25500


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    raw = SRC.read_bytes()
    sha = hashlib.sha256(raw).hexdigest()
    a = json.loads(raw)
    cols, rows = a["half_grid"]
    tx, ty = a["tiles"]
    assert (cols, rows) == (36, 64) and (tx, ty) == (18, 32)
    bits = a["bits"]
    WATER, NODEPLOY = bits["WATER"], bits["NO_DEPLOY"]
    grid = a["grid"]
    assert len(grid) == rows and all(len(r) == cols for r in grid)

    # --- checks against SPEC §3 -------------------------------------------------
    # river rows y in [15000, 17000) = half rows 30..33, water except the bridges
    bridges = [(b["half_cols"][0], b["half_cols"][1]) for b in a["bridges"]]
    assert bridges == [(5, 8), (27, 30)], bridges
    for r in range(rows):
        for c in range(cols):
            water = bool(grid[r][c] & WATER)
            on_bridge = any(lo <= c <= hi for lo, hi in bridges)
            want = 30 <= r <= 33 and not on_bridge
            assert water == want, (r, c, grid[r][c])

    kings = a["king_blocks"]
    king_top = (int(kings[0]["center"][0] * 1000), int(kings[0]["center"][1] * 1000))
    king_bot = (int(kings[1]["center"][0] * 1000), int(kings[1]["center"][1] * 1000))
    assert king_top == (9000, 3000) and king_bot == (9000, 29000), (king_top, king_bot)
    bx = [int(b["center_x"] * 1000) for b in a["bridges"]]
    assert bx == [3500, 14500], bx

    tile_flags = [[0] * tx for _ in range(ty)]
    for y in range(ty):
        for x in range(tx):
            f = 0
            for dy in (0, 1):
                for dx in (0, 1):
                    v = grid[2 * y + dy][2 * x + dx]
                    if v & WATER:
                        f |= 1
                    if v & NODEPLOY:
                        f |= 2
            tile_flags[y][x] = f

    # --- render --------------------------------------------------------------------
    out = []
    out.append("/*")
    out.append(" * pr_arena_db.h -- GENERATED by tools/gen_arena.py. DO NOT EDIT BY HAND.")
    out.append(" *")
    out.append(" * Source: data/source/royalesim-arena.json (RoyaleSim 72ed062, 2018 tilemap)")
    out.append(f" * Source sha256: {sha}")
    out.append(" * Engine frame: x in [0, 18000), y in [0, 32000), y = 0 is the TOP (team 1) edge.")
    out.append(" */")
    out.append("#ifndef PR_ARENA_DB_H")
    out.append("#define PR_ARENA_DB_H")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("")
    out.append(f'#define PR_ARENA_SHA256 "{sha}"')
    out.append("#define PR_ARENA_W 18000")
    out.append("#define PR_ARENA_H 32000")
    out.append("#define PR_TILES_X 18")
    out.append("#define PR_TILES_Y 32")
    out.append("#define PR_CELL 500          /* half-tile cell size, millitiles */")
    out.append("#define PR_COLS 36")
    out.append("#define PR_ROWS 64")
    out.append("#define PR_N_CELLS (PR_COLS * PR_ROWS)")
    out.append("")
    out.append(f"#define PR_CB_LANE_LEFT {bits['LANE_LEFT']}")
    out.append(f"#define PR_CB_LANE_RIGHT {bits['LANE_RIGHT']}")
    out.append(f"#define PR_CB_NODEPLOY {NODEPLOY}")
    out.append(f"#define PR_CB_WATER {WATER}")
    out.append("")
    out.append("/* per-tile flags */")
    out.append("#define PR_TF_WATER 1")
    out.append("#define PR_TF_NODEPLOY 2")
    out.append("")
    out.append("/* river band and bridges (SPEC §3) */")
    out.append("#define PR_RIVER_Y0 15000")
    out.append("#define PR_RIVER_Y1 17000      /* exclusive */")
    out.append(f"#define PR_BRIDGE_L_X0 {bridges[0][0] * 500}")
    out.append(f"#define PR_BRIDGE_L_X1 {(bridges[0][1] + 1) * 500}   /* exclusive */")
    out.append(f"#define PR_BRIDGE_R_X0 {bridges[1][0] * 500}")
    out.append(f"#define PR_BRIDGE_R_X1 {(bridges[1][1] + 1) * 500}  /* exclusive */")
    out.append("")
    out.append("/* crown tower centres, engine frame, [team][0=King, 1=Left, 2=Right] (SPEC §3) */")
    out.append("static const int32_t PR_TOWER_POS[2][3][2] = {")
    out.append(f"    {{{{{king_bot[0]}, {king_bot[1]}}}, {{{bx[0]}, {PRINCESS_Y_BOTTOM}}}, "
               f"{{{bx[1]}, {PRINCESS_Y_BOTTOM}}}}},  /* team 0 (bottom) */")
    out.append(f"    {{{{{king_top[0]}, {king_top[1]}}}, {{{bx[0]}, {PRINCESS_Y_TOP}}}, "
               f"{{{bx[1]}, {PRINCESS_Y_TOP}}}}},  /* team 1 (top) */")
    out.append("};")
    out.append("")
    out.append("/* half-tile cell bitmask [row = y / 500][col = x / 500] */")
    out.append("static const uint8_t PR_CELL_BITS[PR_ROWS][PR_COLS] = {")
    for r in range(rows):
        out.append("    {" + ",".join(f"{v:2d}" for v in grid[r]) + "},")
    out.append("};")
    out.append("")
    out.append("/* whole-tile flags [ty][tx], engine frame */")
    out.append("static const uint8_t PR_TILE_FLAGS[PR_TILES_Y][PR_TILES_X] = {")
    for y in range(ty):
        out.append("    {" + ",".join(str(v) for v in tile_flags[y]) + "},  /* ty=" + str(y) + " */")
    out.append("};")
    out.append("")
    out.append("#endif /* PR_ARENA_DB_H */")
    text = "\n".join(out) + "\n"

    if args.check:
        cur = OUT.read_text() if OUT.exists() else ""
        if cur != text:
            print(f"{OUT} is stale; run `make gen`", file=sys.stderr)
            return 1
        print(f"{OUT.relative_to(ROOT)} up to date")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
